version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongod-fiap
    environment:
      MONGODB_USER: root
      MONGODB_DATABASE: root
      MONGODB_PASS: bancoFiap
      MONGO_INITDB_DATABASE: bancoFiap
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped